version: "3.8"

services:
  productmanagement-api:
    image: saulodias/product-management:latest #Docker Hub
    container_name: product-management-api-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://productmanagement-db:5432/productmanagement
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_secret
    depends_on:
      - productmanagement-db
    restart: always

  productmanagement-db:
    image: postgres:15.0-alpine
    container_name: productmanagement-db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_secret
      POSTGRES_DB: productmanagement
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: