server:
  port: 8080

logging:
  level:
    root: info

spring:
  application:
    name: "product-management"
  datasource:
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: product_schema
    create-schemas: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
      discovery:
        enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always

info:
  app:
    name: Product Manager
    description: "API REST para gerenciamento de produtos com controle de estoque e operações CRUD integradas."
    version: 1.0.0
    database: H2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs



